/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/**/*.{html,ts}'
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#8ed0ea",
        "inverse-on-surface": "#eff1f2",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffdcc2",
        "secondary-fixed": "#d3e5ed",
        "on-error": "#ffffff",
        "primary": "#146279",
        "on-background": "#191c1d",
        "surface-bright": "#f8fafb",
        "surface-dim": "#d8dadb",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#6a3b0a",
        "secondary-fixed-dim": "#b7c9d1",
        "on-secondary": "#ffffff",
        "outline-variant": "#bfc8cc",
        "tertiary": "#814e1d",
        "surface-container-high": "#e6e8e9",
        "on-secondary-container": "#54656c",
        "primary-fixed": "#b9eaff",
        "on-secondary-fixed": "#0d1e24",
        "surface-container": "#eceeef",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#2e1500",
        "on-primary": "#ffffff",
        "surface-container-low": "#f2f4f5",
        "surface-container-highest": "#e1e3e4",
        "on-secondary-fixed-variant": "#394950",
        "secondary": "#506168",
        "on-surface": "#191c1d",
        "primary-container": "#367b93",
        "tertiary-container": "#9e6633",
        "on-surface-variant": "#40484c",
        "outline": "#70787d",
        "primary-fixed-dim": "#8ed0ea",
        "tertiary-fixed-dim": "#fdb87d",
        "on-primary-container": "#f4fbff",
        "background": "#f8fafb",
        "error-container": "#ffdad6",
        "surface": "#f8fafb",
        "on-tertiary-container": "#fff8f5",
        "on-primary-fixed-variant": "#004d62",
        "on-primary-fixed": "#001f29",
        "secondary-container": "#d0e3eb",
        "surface-tint": "#1b667d",
        "inverse-surface": "#2e3132",
        "surface-variant": "#e1e3e4",
        "d-surface": "#131315",
        "d-surface-container-lowest": "#0e0e10",
        "d-surface-container-low": "#1c1b1d",
        "d-surface-container": "#201f22",
        "d-surface-container-high": "#2a2a2c",
        "d-surface-container-highest": "#353437",
        "d-surface-lowest": "#09090b",
        "d-outline": "#889297",
        "d-outline-variant": "#3f484c",
        "d-primary": "#80d1f0",
        "d-on-surface": "#e5e1e4",
        "d-on-surface-variant": "#bec8cd"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "max-width": "1280px",
        "gutter": "24px",
        "base": "8px",
        "margin-mobile": "16px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "label-caps": ["Geist", "sans-serif"],
        "code-sm": ["Geist Mono", "JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-xl": ["Hanken Grotesk", "sans-serif"]
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "code-sm": ["13px", { lineHeight: "20px", fontWeight: "450" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    }
  },
  plugins: [],
}
